/* SEO title and meta description copy, one entry per URL.

   WHY THIS FILE EXISTS AT ALL. Every converted page on the install carries
   NO meta description: zero characters, all sixteen of them. The legacy
   Beaver pages beside them (/home/, /team-old/, /donate-old/, /learn-more/)
   all have one, 340-410 characters long, obviously auto-generated by All in
   One SEO from the page's own text and reading like it ("Mississippians
   committed to MississippiOur team is led by Mi..."). The difference is not
   a setting, it is the conversion: AIOSEO's auto-generator reads
   post_content, and an Elementor page's post_content is empty, because its
   text lives in _elementor_data. So the very act of converting a page
   silently strips its description. Nothing warns about it, and nothing in
   the conversion pipeline put one back.

   The same mechanism has the opposite effect on the `person` CPT: those
   posts DO have post_content, so every bio has a description, and every one
   of them is 359-416 characters, i.e. more than twice what Google will show.
   They are not missing, they are unusable, which is a different defect with
   the same fix: write one.

   WHO IS IN HERE CHANGED ON 2026-08-21. The sheet went to Empower with
   eighteen bios and came back with five rows emptied: Wil Ervin, Brett
   Kittredge, Steven Randle, Katie Elliott and Christopher Koopman. That
   reads as a staff change rather than an edit, and the rest of the returned
   document agrees with it - Wil Ervin's name was taken out of the Capitol
   Chat description in the same pass, and Kienna Horn now carries the
   Communications title Brett Kittredge held. On Paolo's decision the five
   listings were deleted here and the five posts set to draft on the install,
   so the thirteen below are exactly the thirteen published `person` entries.
   test-elementor.mjs asserts that correspondence against the install rather
   than against this count.

   TARGETS (checked by test-elementor.mjs, not by eye):
     title       45-60 characters INCLUDING the " - Empower Mississippi"
                 suffix, which is 22 of them. Over 60 truncates; under 45
                 wastes the pixel width Google gives us. The band is 45 and
                 not the usually-quoted 50 because of the bios: a title is
                 "<name>, <role>", and a long name (Dr. Kristin Vance
                 Richards) leaves no room for a role without truncating the
                 name, which is the half someone searching actually typed.
     description 140-160 characters, and the first ~110 must stand alone,
                 because that is all a phone shows.

   Every description here is written from the page's OWN signed-off copy, or
   from the person's own bio. Nothing is invented, and no figure appears here
   that does not appear on the page it describes (Empower's no-invented-
   statistics rule applies to a search snippet exactly as it applies to a
   heading). Google rewrites 60-70% of descriptions anyway; the one thing
   that makes a rewrite MORE likely is a description the page does not
   deliver on.

   The key is the path, not the page directory name, because the person CPT
   entries have no page directory and the two are not the same set. */

export const BRAND_SUFFIX = ' - Empower Mississippi';

/* The sixteen converted pages. */
export const PAGE_SEO = {
  '/': {
    title: 'Expanding Opportunity in Mississippi',
    description:
      'Empower Mississippi works to expand opportunity so every Mississippian '
      + 'can build a good life at home: quality education, meaningful work and '
      + 'safer communities.',
    /* The post title on the install is "Homepage (Elementor conversion)",
       which is a build artefact and is currently what a browser tab and a
       search result both say. This override is what replaces it; the post
       title itself is deliberately NOT renamed, because the conversion
       tests and the deploy scripts find the page by it. */
  },
  '/what-we-do/': {
    title: 'What We Do: Research Into Solutions',
    description:
      'How Empower Mississippi turns research into practical policy across '
      + 'quality education, meaningful work and public safety. Read our latest '
      + 'annual reports.',
  },
  '/solutions/': {
    title: 'Practical Solutions for Mississippi',
    description:
      'Three areas where practical solutions expand opportunity: quality '
      + 'education, meaningful work and safer communities. See how research '
      + 'becomes lasting change.',
  },
  '/capitol-chat/': {
    title: 'Capitol Chat: Legislative Updates',
    description:
      "Empower Mississippi's weekly insider update on the State Capitol. We "
      + "break down the session's biggest developments in under five "
      + 'minutes.',
  },
  '/who-we-are/': {
    title: 'Who We Are: Our Mission and Team',
    description:
      'Empower Mississippi exists so every Mississippian can achieve the '
      + 'American Dream here at home. Meet the team and read the story behind '
      + 'the work.',
  },
  '/newsletter/': {
    title: 'Email Sign Up: Stay Connected',
    description:
      'Get the latest from Empower Mississippi by email: one update a month, '
      + 'plus news from the Capitol while the session runs. Five minutes or '
      + 'less.',
  },
  '/ambassadors/': {
    title: 'Become an Empower Ambassador',
    description:
      'Join a network of parents, educators, business owners and community '
      + 'leaders advancing practical solutions for Mississippi. Your voice '
      + 'matters here.',
  },
  '/epic/': {
    title: 'EPIC: Mississippi Policy Research',
    description:
      'The Empower Policy & Innovation Center produces Mississippi-specific '
      + 'research on education, work and public safety, built with the people '
      + 'policy affects.',
  },
  '/donate/': {
    title: 'Donate to Expand Opportunity',
    description:
      'Your gift advances practical solutions that expand educational '
      + 'opportunity, strengthen the workforce and build safer communities. '
      + 'Empower is a 501(c)(3).',
  },
  '/public-safety/': {
    title: 'Public Safety in Mississippi',
    description:
      'Safer communities start with preventing crime, supporting effective law '
      + 'enforcement, strengthening families and a justice system that is both '
      + 'safe and fair.',
  },
  '/meaningful-work/': {
    title: 'Meaningful Work in Mississippi',
    description:
      'Too many Mississippians are disconnected from work. We work to remove '
      + 'barriers so more people can reach good careers, provide for a family '
      + 'and earn success.',
  },
  '/quality-education/': {
    title: 'Quality Education in Mississippi',
    description:
      'Every child learns differently. We work to empower parents, give '
      + 'educators freedom and create more pathways for Mississippi students '
      + 'to learn and succeed.',
  },
  '/podcast/': {
    title: 'The Empower Podcast, with Grant Callen',
    description:
      'Grant Callen talks with lawmakers, policy experts and community leaders '
      + "about Mississippi's biggest challenges and the solutions that help "
      + 'Mississippi rise.',
  },
  '/all-content/': {
    title: 'All Content: Articles and Research',
    description:
      'Everything Empower Mississippi publishes, in one place: articles, '
      + 'community stories, research and reports, and press releases. Filter '
      + 'by topic or by type.',
  },
  '/team/': {
    title: 'Meet Our Team, Board and Fellows',
    description:
      'Meet the staff, board members and fellows behind Empower Mississippi, '
      + "working to create a path to generational prosperity for the state's "
      + 'families.',
  },
  /* The bio TEMPLATE page, converted from the signed-off team-bio design and
     filled with Grant Callen. It is a duplicate of /person/grant-callen/ in
     everything a search engine reads: same person, same name in the title,
     each canonical to itself. That is a real defect and this file cannot fix
     it, because the fix is a decision about which URL is the bio (see the
     note at the bottom of this file). The description here is written so
     that IF the page stays, the two are at least not word-for-word
     identical. */
  '/grant-callen/': {
    title: 'Grant Callen, Founder and CEO',
    description:
      'Grant Callen founded Empower Mississippi in 2014 as a solution center '
      + "for the state's biggest challenges. A sixth generation Mississippian "
      + 'from Laurel.',
  },
};

/* The thirteen published `person` CPT bios. Titles carry the role where the name is
   short enough for the pair to fit under 60 characters with the suffix, and
   the name alone where it is not; role in a title is worth having (it is
   what someone searching a name is trying to confirm) but not worth
   truncating the name for. Descriptions are cut from each person's own bio,
   first job first. */
export const PERSON_SEO = {
  '/person/grant-callen/': {
    title: 'Grant Callen, Founder and CEO',
    description:
      'Founder and CEO of Empower Mississippi, started in 2014. A sixth '
      + 'generation Mississippian from Laurel, previously at Mississippi '
      + 'Center for Public Policy.',
  },
  '/person/gina-metzger/': {
    /* 64 with the suffix, over the 60 the band asks for. Empower's own
       wording, kept verbatim on Paolo's 2026-08-21 decision that the returned
       document wins over the band: what truncates is the tail of the brand
       suffix, and the name and the role both survive intact. Exempted by path
       in test-elementor.mjs, not by widening the band for everybody. */
    title: 'Gina Metzger, Chief Administrative Officer',
    description:
      'Executive Vice President at Empower Mississippi, overseeing day-to-day '
      + 'operations and every Empower event. A University of Mississippi '
      + 'graduate.',
  },
  '/person/patrick-miller-2/': {
    /* Promoted between the sheet going out and coming back: he was VP
       Development, he is Executive Vice President, and the description is
       Empower's replacement rather than an edit of ours. 66 with the suffix
       and 164 characters of description, both over, both kept verbatim for
       the same reason as Gina Metzger above. The description is the one
       exemption with a visible cost: Google clips it around four characters
       short of the full stop. */
    title: 'Dr. Patrick Miller, Executive Vice President',
    description:
      'Dr. Patrick Miller is Executive Vice President at Empower Mississippi, '
      + 'leading organizational execution, team alignment, fundraising, and '
      + 'institutional advancement.',
  },
  '/person/dr-kristin-vance-richards/': {
    title: 'Dr. Kristin Vance Richards',
    description:
      'Director of Research at Empower Mississippi, leading the research that '
      + 'shapes data-driven strategy across education, work and criminal '
      + 'justice.',
  },
  '/person/kienna-horn/': {
    title: 'Kienna Horn, Communications',
    description:
      "Director of Communications at Empower Mississippi, leading media "
      + 'relations, issue campaigns and content. Journalism graduate of '
      + 'Mississippi College.',
  },
  '/person/ashley-green/': {
    title: 'Ashley Green, Director of Outreach',
    description:
      'Director of Outreach at Empower Mississippi, connecting with the people '
      + 'most affected by policy in education, work and criminal justice, '
      + 'elevating their voices.',
  },
  '/person/forest-thigpen/': {
    title: 'Forest Thigpen, Senior Advisor',
    description:
      'Senior Advisor at Empower Mississippi, with nearly three decades at the '
      + 'State Capitol. He founded the Mississippi Center for Public Policy in '
      + '1993.',
  },
  '/person/joanna-polk-2/': {
    title: 'Joanna Polk, Development Manager',
    description:
      'Executive Assistant and Development Manager at Empower Mississippi, '
      + 'supporting the CEO, the strategic fundraising plan and new donor '
      + 'relationships.',
  },
  '/person/elyse-marcellino/': {
    title: 'Elyse Marcellino, Embark Director',
    description:
      'Director of Embark, helping education entrepreneurs open high-quality '
      + 'charter and private schools in Mississippi. She helped launch Atlanta '
      + 'Classical Academy.',
  },
  '/person/donald-nielsen/': {
    title: 'Donald Nielsen, Empower Fellow',
    description:
      'Empower Mississippi fellow. Senior Fellow of Discovery Institute, chair '
      + 'of its public education reform program, and Chairman of Lumenal '
      + 'Lighting.',
  },
  '/person/joe-bishop-henchman/': {
    title: 'Joe Bishop-Henchman, Fellow',
    description:
      'Empower Mississippi fellow. Vice President of Policy and Litigation at '
      + "National Taxpayers Union Foundation, leading NTUF's Taxpayer Defense "
      + 'Center.',
  },
  '/person/matt-ladner/': {
    title: 'Dr. Matthew Ladner, Fellow',
    description:
      'Empower Mississippi fellow. Director of the Arizona Center for Student '
      + 'Opportunity and Executive Editor of RedefinED, previously at the '
      + 'Goldwater Institute.',
  },
  '/person/conor-norris/': {
    title: 'Conor Norris, Empower Fellow',
    description:
      'Empower Mississippi fellow. Research analyst with the Knee Center for '
      + 'the Study of Occupational Regulation, studying how licensing affects '
      + 'work and enterprise.',
  },
};

export const ALL_SEO = { ...PAGE_SEO, ...PERSON_SEO };

/* What a page's <title> will actually say, suffix included. */
export function fullTitle(path) {
  const entry = ALL_SEO[path];
  return entry ? entry.title + BRAND_SUFFIX : null;
}

/* THE ONE THING THIS FILE CANNOT DECIDE. /grant-callen/ and
   /person/grant-callen/ both return 200, both are titled "Grant Callen",
   both canonical to themselves, and both carry the same bio. Whichever way
   Empower want it, the fix is one of:
     - retire /grant-callen/ (it was a design template fill, not a picked
       page), or
     - noindex it, or
     - canonical it to /person/grant-callen/.
   Doing nothing means the two compete, and Google picks one. */
