# (page, index_in_page) -> (source, output-name, css_w, css_h, y-gravity)
# index_in_page is document order of photography <img> in the built page.
# MOCKUP = leave the tag alone.
PLAN = {
 'final': {
   0:("DSCF0129","school-leader-outside",      549,686,0.35),
   1:("P1277564","student-writing-overhead",   168,168,0.50),
   2:("DSCF0144","student-hand-raised",        374,600,0.30),
   3:("DSCF0324","warehouse-worker-pallet",    374,600,0.30),
   4:("DSCF0392","advocate-capitol-portrait",  374,600,0.25),
   5:("DSCF0192","shop-owner-portrait",        256,374,0.25),
   6:("DSCF0295","worker-labelling-sq",         80, 80,0.28),
   7:("DSCF0346","maker-with-laptop-sq",        80, 80,0.28),
   8:("DSCF0222","gift-boxes-detail",          184,172,0.50),
   9:"MOCKUP",
  10:("DSCF0139","teacher-student-desk",       184,172,0.40),
  11:("DSCF0339","two-workers-boxes",          558,307,0.45),
  12:("DSCF0570","advocates-capitol-steps",    558,307,0.40),
 },
 'who-we-are-a': {
   0:("DSCF0434","advocates-capitol-rail",     560,373,0.40),
   1:("DSCF0163","teacher-with-student",       211,286,0.35),
   2:("P1277569","teacher-at-whiteboard",      519,389,0.45),
   3:("DSCF0209","shop-owner-standing",        190,253,0.30),
   4:("DSCF0323","warehouse-worker-aisle",     190,253,0.30),
   5:("DSCF0595","advocate-outdoors",          190,253,0.30),
 },
 'what-we-do-a': {
   0:("DSCF0169","school-leader-crest",        510,637,0.30),
   1:("DSCF0143","classroom-small-group",      361,271,0.45),
   2:("DSCF0329","worker-at-bench",            361,271,0.45),
   3:("DSCF0450","advocates-capitol-hall",     361,271,0.45),
 },
 'team-a': {
   0:("DSCF0399","two-advocates-portrait",     453,566,0.25),
 },
 'solutions-b': {
   0:("DSCF0143","classroom-small-group-54",   398,318,0.45),
   1:("DSCF0329","worker-at-bench-54",         398,318,0.45),
   2:("DSCF0450","advocates-capitol-hall-54",  398,318,0.45),
   3:("DSCF0436","advocates-in-conversation-wide",1425,374,0.42),
 },
 'education': {
   0:("DSCF0147","students-working-quietly",   502,377,0.45),
   1:("P1277559","teacher-small-group-wide",  1425,611,0.45),
 },
 'work': {
   0:("DSCF0303","worker-sorting-table",       502,377,0.45),
   1:("DSCF0292","worker-labelling-wide",     1425,611,0.42),
 },
 'epic-a': {
   0:("DSCF0323","warehouse-worker-aisle-43",  450,338,0.35),
   1:("DSCF0141","teacher-smartboard",         355,266,0.42),
   2:("DSCF0284","hands-with-product",         355,266,0.50),
   3:("DSCF0572","advocates-outside-capitol",  355,266,0.40),
 },
 'mail-a': {
   0:"MOCKUP",
   1:("DSCF0174","teacher-yellow-portrait",    450,600,0.25),
 },
 'amb-a': {
   0:("DSCF0211","shop-owner-counter",         450,563,0.28),
   1:("DSCF0284","hands-with-product-sq",      303,303,0.50),
   2:("DSCF0138","worksheet-overhead",         303,303,0.50),
   3:("DSCF0346","maker-with-laptop",          303,379,0.28),
   4:("DSCF0386","advocate-portrait-blue",     303,379,0.25),
 },
 'give-c': {
   0:("DSCF0163","teacher-with-student-45",    301,376,0.35),
   1:("DSCF0332","worker-packing-smiling",     301,376,0.30),
 },
 # 'safety' deliberately absent: held pending Kienna on the second-chances question.
}
ALT = {
 "school-leader-outside":"A woman in a purple school blazer standing on a path outside the academy building",
 "school-leader-crest":"A woman in a purple school blazer standing in front of the academy crest",
 "student-hand-raised":"A girl in school uniform raising her hand at a classroom table",
 "student-writing-overhead":"Two children writing on lined paper at a yellow classroom table, seen from above",
 "worksheet-overhead":"A boy drawing a diagram on a worksheet, seen from above",
 "classroom-small-group":"A girl raising her hand while classmates write at a shared table",
 "classroom-small-group-54":"A girl raising her hand while classmates write at a shared table",
 "teacher-student-desk":"A teacher in a purple shirt sitting beside a smiling student at a classroom table",
 "teacher-with-student":"A teacher and a student standing together in front of a school mission statement",
 "teacher-with-student-45":"A teacher and a student standing together in front of a school mission statement",
 "teacher-at-whiteboard":"A teacher writing a maths diagram on a whiteboard while students work",
 "teacher-smartboard":"A teacher working through a maths problem on a smartboard with her class",
 "teacher-small-group-wide":"Two teachers helping several children with written work at a classroom table",
 "teacher-yellow-portrait":"A teacher in a yellow cardigan standing in a school corridor",
 "students-working-quietly":"Two students working at laptops and notebooks in a classroom",
 "shop-owner-portrait":"A shop owner standing at the counter of her gift shop",
 "shop-owner-standing":"A shop owner standing beside shelves of stock in her shop",
 "shop-owner-counter":"A shop owner leaning on the counter of her gift shop",
 "gift-boxes-detail":"Wrapped gift items in tissue paper arranged in a bowl",
 "hands-with-product":"A worker’s hands fitting a printed label to a product lid",
 "hands-with-product-sq":"A worker’s hands fitting a printed label to a product lid",
 "maker-with-laptop":"A woman holding a laptop in a production room lined with storage crates",
 "maker-with-laptop-sq":"A woman holding a laptop in a production room lined with storage crates",
 "worker-at-bench":"A woman trimming material at a packing bench",
 "worker-at-bench-54":"A woman trimming material at a packing bench",
 "worker-labelling-sq":"A woman winding a roll of printed labels at a work table",
 "worker-labelling-wide":"A woman winding a roll of printed labels at a work table",
 "worker-sorting-table":"A woman filling a box at a packing table",
 "worker-packing-smiling":"A woman cutting material at a packing bench",
 "warehouse-worker-pallet":"A man standing with a pallet truck in a warehouse aisle",
 "warehouse-worker-aisle":"A man standing with a pallet truck between warehouse racks",
 "warehouse-worker-aisle-43":"A man standing with a pallet truck between warehouse racks",
 "two-workers-boxes":"Two workers standing beside stacked boxes on a warehouse floor",
 "advocate-capitol-portrait":"A man standing in the Capitol rotunda",
 "advocate-outdoors":"A man standing outdoors under trees",
 "advocate-portrait-blue":"A woman standing at the balustrade inside the Capitol",
 "two-advocates-portrait":"A woman and a man standing together inside the Capitol",
 "advocates-in-conversation-wide":"A man and a woman talking beside a rail inside the Capitol",
 "advocates-capitol-rail":"A man and a woman talking across a rail inside the Capitol",
 "advocates-capitol-hall":"A man and a woman talking in a Capitol corridor",
 "advocates-capitol-hall-54":"A man and a woman talking in a Capitol corridor",
 "advocates-capitol-steps":"A man and a woman talking outside the Capitol",
 "advocates-outside-capitol":"A man and a woman talking on the Capitol steps",
}
